FROM golang:1.20 as build
WORKDIR /src

COPY cmd/ cmd
COPY pkg/ pkg
COPY internal/ internal
COPY go.mod go.mod
COPY go.sum go.sum

RUN go build -o server cmd/worker/main.go

FROM centos:6.6 as production

WORKDIR /srv

COPY --from=build /src/server server
